spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/conflicttracker
    username: safu
    password: 2006

  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
